#ifndef GIGASTT_H
#define GIGASTT_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque C type. Never constructed — returned pointers are table ids.
 */
typedef struct GigasttEngine GigasttEngine;

/**
 * Opaque C type. Never constructed — returned pointers are table ids.
 */
typedef struct GigasttStream GigasttStream;

/**
 * Load the ONNX models from `model_dir` and create an inference engine.
 *
 * Uses the default pool size (2). For mobile devices, prefer
 * `gigastt_engine_new_with_pool_size` with `pool_size = 1` to reduce RAM.
 *
 * # Safety
 * `model_dir` must be a valid, null-terminated UTF-8 string.
 * Returns a pointer to a `GigasttEngine` on success, or `NULL` on failure.
 */
struct GigasttEngine *gigastt_engine_new(const char *model_dir);

/**
 * Load the ONNX models with a custom session pool size.
 *
 * `pool_size` controls how many concurrent inference sessions are kept in
 * memory. The INT8 encoder is memory-mapped and shared; an extra slot costs
 * on the order of tens of megabytes resident, not another full model copy:
 * - pool_size = 1: recommended for mobile
 * - pool_size = 2: default desktop/server
 *
 * # Safety
 * `model_dir` must be a valid, null-terminated UTF-8 string.
 * Returns a pointer to a `GigasttEngine` on success, or `NULL` on failure.
 */
struct GigasttEngine *gigastt_engine_new_with_pool_size(const char *model_dir, uintptr_t pool_size);

/**
 * Transcribe an audio file and return the recognized text as a newly allocated C string.
 *
 * # Safety
 * - `engine` must be a non-null pointer returned by `gigastt_engine_new` and not yet freed.
 * - `wav_path` must be a valid, null-terminated UTF-8 string.
 * - A concurrent `gigastt_engine_free` during this call is safe: the table
 *   holds an `Arc` for the duration of the call. A call after free returns
 *   `NULL`.
 *
 * Returns a pointer to a NUL-terminated UTF-8 string on success, or `NULL` on failure.
 * The caller **must** free the returned string with `gigastt_string_free`.
 */
char *gigastt_transcribe_file(struct GigasttEngine *engine, const char *wav_path);

/**
 * Free a C string previously returned by `gigastt_transcribe_file` or the
 * streaming functions.
 *
 * # Safety
 * `s` must be a pointer returned by one of the transcription functions and not
 * yet freed, or `NULL` (in which case this is a no-op).
 */
void gigastt_string_free(char *s);

/**
 * Free an inference engine previously created by `gigastt_engine_new`.
 *
 * # Safety
 * `engine` must be a pointer returned by `gigastt_engine_new` and not yet freed,
 * or `NULL` (in which case this is a no-op). Concurrent free during an
 * in-flight call is safe (the call's `Arc` keeps the engine alive).
 */
void gigastt_engine_free(struct GigasttEngine *engine);

/**
 * Quantize the FP32 encoder model to INT8 in-place.
 *
 * Auto-detects the recognition head present in `model_dir` (the `rnnt` default
 * since v2.3, or `e2e_rnnt`) and quantizes that variant's FP32 encoder, writing
 * the matching `*_int8.onnx` beside it. If the INT8 file already exists and
 * `force` is `false`, returns immediately.
 *
 * # Safety
 * `model_dir` must be a valid, null-terminated UTF-8 string.
 *
 * Returns a newly allocated C string on both success and error.
 * The caller **must** free the returned string with `gigastt_string_free`.
 */
char *gigastt_quantize_model(const char *model_dir, bool force);

/**
 * Create a new streaming session.
 *
 * Checks out a `SessionTriplet` from the engine pool and creates a fresh
 * `StreamingState`. The triplet is held for the lifetime of the stream and
 * returned to the pool by `gigastt_stream_free`.
 *
 * # Safety
 * `engine` must be a valid pointer returned by `gigastt_engine_new`.
 * Returns a pointer to a `GigasttStream` on success, or `NULL` on failure.
 */
struct GigasttStream *gigastt_stream_new(struct GigasttEngine *engine);

/**
 * Process a chunk of PCM16 audio and return any partial/final segments.
 *
 * # Safety
 * - `engine` and `stream` must be valid pointers.
 * - `pcm16_bytes` must point to at least `len` valid bytes (little-endian mono PCM16).
 * - Concurrent free during this call is safe. A call after free returns `NULL`.
 *
 * Returns a newly allocated JSON array string on success, or `NULL` on failure.
 * The caller **must** free the returned string with `gigastt_string_free`.
 */
char *gigastt_stream_process_chunk(struct GigasttEngine *engine,
                                   struct GigasttStream *stream,
                                   const uint8_t *pcm16_bytes,
                                   uintptr_t len,
                                   uint32_t sample_rate);

/**
 * Flush the streaming state and return the final segment(s).
 *
 * # Safety
 * `stream` must be a pointer returned by `gigastt_stream_new`. Concurrent
 * free during this call is safe. A call after free returns `NULL`.
 *
 * Returns a newly allocated JSON array string (possibly `[]`) on success,
 * or `NULL` on failure. The caller **must** free the returned string with
 * `gigastt_string_free`.
 */
char *gigastt_stream_flush(struct GigasttEngine *engine, struct GigasttStream *stream);

/**
 * Free a streaming session and return its triplet to the pool.
 *
 * # Safety
 * `stream` must be a pointer returned by `gigastt_stream_new` and not yet freed,
 * or `NULL` (in which case this is a no-op). Concurrent free during an
 * in-flight call is safe.
 */
void gigastt_stream_free(struct GigasttStream *stream);

#endif  /* GIGASTT_H */
